package Admin.Panels;

import Admin.Dialogs.JDEncargados;
import Util.Conexion;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author jli4n
 */
public class PAdEncargados extends javax.swing.JPanel {

    private Conexion cnx;

    String todos = "SELECT * FROM vw_encargados";
    String tutores = "SELECT * FROM vw_encargados \n"
            + "WHERE tipoEncargado COLLATE utf8mb4_unicode_ci = 'Tutor' COLLATE utf8mb4_unicode_ci;";
    String auxiliares = "SELECT * FROM vw_encargados \n"
            + "WHERE tipoEncargado COLLATE utf8mb4_unicode_ci = 'Auxiliar' COLLATE utf8mb4_unicode_ci;";

    /**
     * Creates new form AdminPersonal
     */
    public PAdEncargados(Conexion cnx) {
        this.cnx = cnx;
        initComponents();
        LDescripcion.setText("Mostrando todos los encargados (tutores y auxiliares)");
        cnx.entablar(todos, TConsultas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jToolBar2 = new javax.swing.JToolBar();
        BTodos = new javax.swing.JButton();
        BTutores = new javax.swing.JButton();
        BAuxiliares = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BNuevo = new javax.swing.JButton();
        BEditar = new javax.swing.JButton();
        BBorrar = new javax.swing.JButton();
        LDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TConsultas = new javax.swing.JTable();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(255, 255, 255));

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setBorder(null);
        jToolBar2.setRollover(true);
        jToolBar2.setBorderPainted(false);

        BTodos.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BTodos.setText("TODOS");
        BTodos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTodos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTodosActionPerformed(evt);
            }
        });
        jToolBar2.add(BTodos);

        BTutores.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BTutores.setText("TUTORES");
        BTutores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTutores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTutoresActionPerformed(evt);
            }
        });
        jToolBar2.add(BTutores);

        BAuxiliares.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BAuxiliares.setText("AUXILIARES");
        BAuxiliares.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BAuxiliares.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BAuxiliares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAuxiliaresActionPerformed(evt);
            }
        });
        jToolBar2.add(BAuxiliares);

        jLabel1.setFont(new java.awt.Font("Anton", 0, 18)); // NOI18N
        jLabel1.setText("Admin / Encargados");

        BNuevo.setBackground(new java.awt.Color(0, 153, 0));
        BNuevo.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BNuevo.setForeground(new java.awt.Color(255, 255, 255));
        BNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/registro.png"))); // NOI18N
        BNuevo.setText("NUEVO");
        BNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNuevoActionPerformed(evt);
            }
        });

        BEditar.setBackground(new java.awt.Color(0, 153, 153));
        BEditar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BEditar.setForeground(new java.awt.Color(255, 255, 255));
        BEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        BEditar.setText("EDITAR");
        BEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditarActionPerformed(evt);
            }
        });

        BBorrar.setBackground(new java.awt.Color(255, 51, 102));
        BBorrar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BBorrar.setForeground(new java.awt.Color(255, 255, 255));
        BBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/borrar.png"))); // NOI18N
        BBorrar.setText("BORRAR");
        BBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarActionPerformed(evt);
            }
        });

        LDescripcion.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        LDescripcion.setText("Descripción de consulta");

        TConsultas.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        TConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TConsultas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(BNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 530, Short.MAX_VALUE))
                    .addComponent(LDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(LDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BBorrarActionPerformed

    private void BTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTodosActionPerformed
        LDescripcion.setText("Mostrando todos los encargados (tutores y auxiliares)");
        cnx.entablar(todos, TConsultas);
    }//GEN-LAST:event_BTodosActionPerformed

    private void BTutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTutoresActionPerformed
        LDescripcion.setText("Mostrando únicamente los tutores registrados");
        cnx.entablar(tutores, TConsultas);
    }//GEN-LAST:event_BTutoresActionPerformed

    private void BAuxiliaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAuxiliaresActionPerformed
        LDescripcion.setText("Mostrando únicamente los auxiliares registrados");
        cnx.entablar(auxiliares, TConsultas);
    }//GEN-LAST:event_BAuxiliaresActionPerformed

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        JDEncargados dialog = new JDEncargados(new javax.swing.JFrame(), true);
        dialog.setTitle("Nuevo Encargado");
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_BNuevoActionPerformed

    private void BEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditarActionPerformed
        JDEncargados dialog = new JDEncargados(new javax.swing.JFrame(), true);
        dialog.setTitle("Editar Encargado");
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_BEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAuxiliares;
    private javax.swing.JButton BBorrar;
    private javax.swing.JButton BEditar;
    private javax.swing.JButton BNuevo;
    private javax.swing.JButton BTodos;
    private javax.swing.JButton BTutores;
    private javax.swing.JLabel LDescripcion;
    private javax.swing.JTable TConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
