package Admin.Panels;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import Util.Conexion;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author jli4n
 */
public class PAdInfantes extends javax.swing.JPanel {

    private Conexion cnx;
    String grupos = "SELECT nombreGrupo FROM grupos ORDER BY nombreGrupo";
    String infantes = "SELECT * FROM infantes";
    String infantesPorGrupos = "SELECT * FROM vw_infantes_por_grupo";

    public PAdInfantes(Conexion cnx) {
        this.cnx = cnx;
        initComponents();

        cnx.entablar(infantes, TConsultas);
        cnx.seleccionar(grupos, CBGrupo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        TBuscar = new javax.swing.JTextField();
        BTodos = new javax.swing.JButton();
        BPorGrupo = new javax.swing.JButton();
        BReporte2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BNuevo = new javax.swing.JButton();
        BEditar = new javax.swing.JButton();
        BBorrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TConsultas = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel3 = new javax.swing.JLabel();
        CBGrupo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setBorder(null);
        jToolBar2.setRollover(true);
        jToolBar2.setBorderPainted(false);

        TBuscar.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        TBuscar.setPreferredSize(new java.awt.Dimension(140, 24));
        jToolBar2.add(TBuscar);

        BTodos.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BTodos.setText("TODOS");
        BTodos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTodos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTodosActionPerformed(evt);
            }
        });
        jToolBar2.add(BTodos);

        BPorGrupo.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BPorGrupo.setText("POR GRUPO");
        BPorGrupo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BPorGrupo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BPorGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPorGrupoActionPerformed(evt);
            }
        });
        jToolBar2.add(BPorGrupo);

        BReporte2.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BReporte2.setText("REPORTE 2");
        BReporte2.setFocusable(false);
        BReporte2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BReporte2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BReporte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReporte2ActionPerformed(evt);
            }
        });
        jToolBar2.add(BReporte2);

        jLabel1.setFont(new java.awt.Font("Anton", 0, 18)); // NOI18N
        jLabel1.setText("Admin / Infantes");

        BNuevo.setBackground(new java.awt.Color(0, 153, 0));
        BNuevo.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BNuevo.setForeground(new java.awt.Color(255, 255, 255));
        BNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/registro.png"))); // NOI18N
        BNuevo.setText("NUEVO");
        BNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BEditar.setBackground(new java.awt.Color(0, 153, 153));
        BEditar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BEditar.setForeground(new java.awt.Color(255, 255, 255));
        BEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        BEditar.setText("EDITAR");
        BEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        BBorrar.setBackground(new java.awt.Color(255, 51, 102));
        BBorrar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BBorrar.setForeground(new java.awt.Color(255, 255, 255));
        BBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/borrar.png"))); // NOI18N
        BBorrar.setText("BORRAR");
        BBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel2.setText("Descripción de consulta");

        TConsultas.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        TConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TConsultas);

        jToolBar1.setRollover(true);

        jLabel3.setText("Grupo:");
        jToolBar1.add(jLabel3);

        CBGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBGrupo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBGrupoItemStateChanged(evt);
            }
        });
        jToolBar1.add(CBGrupo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BNuevo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BEditar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BBorrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BBorrarActionPerformed

    private void BTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTodosActionPerformed
        cnx.entablar(infantes, TConsultas);
    }//GEN-LAST:event_BTodosActionPerformed

    private void BPorGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPorGrupoActionPerformed
        //cnx.entablar(infantesPorGrupos, TConsultas);
        
        if (CBGrupo.getSelectedIndex() == 0) {
            cnx.entablar(infantesPorGrupos, TConsultas);
            return;
        }
        
        String grupo = CBGrupo.getSelectedItem().toString();
        String sql = infantesPorGrupos + " WHERE nombreGrupo = " + grupo;
        cnx.entablar(sql, TConsultas);
    }//GEN-LAST:event_BPorGrupoActionPerformed

    private void BReporte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReporte2ActionPerformed
        if (CBGrupo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un grupo");
            return;
        }

        String reporte = System.getProperty("user.dir") + "/infantes_por_grupo.jasper";
        Map parametros = new HashMap();
        parametros.put("grupo", CBGrupo.getSelectedItem().toString());

        System.out.println("Intentando abrir reporte: " + reporte);
        if (cnx.ejecutarReporte(reporte, parametros) == 0) {
            JOptionPane.showMessageDialog(this,
                    "Error al ejecutar el reporte.\nVerifique la consola para más detalles.\nArchivo: " + reporte,
                    "Error en Reporte 1",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BReporte2ActionPerformed

    private void CBGrupoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBGrupoItemStateChanged
        if (CBGrupo.getSelectedIndex() == 0) {
            cnx.entablar(infantesPorGrupos, TConsultas);
            return;
        }
        
        String grupo = CBGrupo.getSelectedItem().toString();
        String sql = infantesPorGrupos + " WHERE nombreGrupo = '" + grupo + "'";
        cnx.entablar(sql, TConsultas);
    }//GEN-LAST:event_CBGrupoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBorrar;
    private javax.swing.JButton BEditar;
    private javax.swing.JButton BNuevo;
    private javax.swing.JButton BPorGrupo;
    private javax.swing.JButton BReporte2;
    private javax.swing.JButton BTodos;
    private javax.swing.JComboBox<String> CBGrupo;
    private javax.swing.JTextField TBuscar;
    private javax.swing.JTable TConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
