package Admin.Panels;

import Admin.Dialogs.JDPersonal;
import Util.Conexion;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author jli4n
 */
public class PAdPersonal extends javax.swing.JPanel {

    private Conexion cnx;

    String todos = "SELECT * FROM vw_personal";
    String admins = "SELECT idUsuario, nombreUsuario AS Usuario, tipoUsuario FROM usuarios WHERE tipoUsuario='Administrador'";
    String educadores = "SELECT e.idEducadora, e.nombreedu AS Nombre, e.telefono AS Telefono, u.nombreUsuario AS Usuario FROM educadoras e INNER JOIN usuarios u ON e.idUsuario=u.idUsuario WHERE u.tipoUsuario='Educadora'";

    /**
     * Creates new form AdminPersonal
     */
    public PAdPersonal(Conexion cnx) {
        this.cnx = cnx;
        initComponents();
        LDescripcion.setText("Lista completa del personal");
        cnx.entablar("SELECT * FROM vw_personal", TConsultas);
        
        DefaultTableModel modelo = (DefaultTableModel) TConsultas.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
        TConsultas.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        TBuscar = new javax.swing.JTextField();
        BTodos = new javax.swing.JButton();
        BAdmins = new javax.swing.JButton();
        BEdus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BNuevo = new javax.swing.JButton();
        BEditar = new javax.swing.JButton();
        BBorrar = new javax.swing.JButton();
        LDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TConsultas = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setBorder(null);
        jToolBar2.setRollover(true);
        jToolBar2.setBorderPainted(false);

        TBuscar.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        TBuscar.setPreferredSize(new java.awt.Dimension(140, 24));
        TBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TBuscarKeyReleased(evt);
            }
        });
        jToolBar2.add(TBuscar);

        BTodos.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BTodos.setText("TODOS");
        BTodos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTodos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTodosActionPerformed(evt);
            }
        });
        jToolBar2.add(BTodos);

        BAdmins.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BAdmins.setText("ADMINs");
        BAdmins.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BAdmins.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAdminsActionPerformed(evt);
            }
        });
        jToolBar2.add(BAdmins);

        BEdus.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BEdus.setText("EDUCADORES");
        BEdus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEdus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BEdus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEdusActionPerformed(evt);
            }
        });
        jToolBar2.add(BEdus);

        jLabel1.setFont(new java.awt.Font("Anton", 0, 18)); // NOI18N
        jLabel1.setText("Admin / Personal");

        BNuevo.setBackground(new java.awt.Color(0, 153, 0));
        BNuevo.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BNuevo.setForeground(new java.awt.Color(255, 255, 255));
        BNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/registro.png"))); // NOI18N
        BNuevo.setText("NUEVO");
        BNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNuevoActionPerformed(evt);
            }
        });

        BEditar.setBackground(new java.awt.Color(0, 153, 153));
        BEditar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BEditar.setForeground(new java.awt.Color(255, 255, 255));
        BEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        BEditar.setText("EDITAR");
        BEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEditarActionPerformed(evt);
            }
        });

        BBorrar.setBackground(new java.awt.Color(255, 51, 102));
        BBorrar.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        BBorrar.setForeground(new java.awt.Color(255, 255, 255));
        BBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/borrar.png"))); // NOI18N
        BBorrar.setText("BORRAR");
        BBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarActionPerformed(evt);
            }
        });

        LDescripcion.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        LDescripcion.setText("Descripción de consulta");

        TConsultas.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        TConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TConsultas.setMaximumSize(null);
        TConsultas.setMinimumSize(null);
        TConsultas.setPreferredSize(null);
        jScrollPane1.setViewportView(TConsultas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 596, Short.MAX_VALUE))
                    .addComponent(LDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(LDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BBorrarActionPerformed

    private void BTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTodosActionPerformed
        LDescripcion.setText("Lista completa del personal");
        cnx.entablar(todos, TConsultas);
    }//GEN-LAST:event_BTodosActionPerformed

    private void BAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAdminsActionPerformed
        LDescripcion.setText("Lista de los administradores");
        cnx.entablar(admins, TConsultas);
    }//GEN-LAST:event_BAdminsActionPerformed

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        JDPersonal dialog = new JDPersonal(new javax.swing.JFrame(), true);
        dialog.setTitle("Nuevo Personal");
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_BNuevoActionPerformed

    private void BEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEditarActionPerformed
        JDPersonal dialog = new JDPersonal(new javax.swing.JFrame(), true);
        dialog.setTitle("Editar Personal");
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_BEditarActionPerformed

    private void BEdusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEdusActionPerformed
        LDescripcion.setText("Lista de los educadores");
        cnx.entablar(educadores, TConsultas);
    }//GEN-LAST:event_BEdusActionPerformed

    private void TBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TBuscarKeyReleased
        String texto = TBuscar.getText().trim();
        LDescripcion.setText("Resultados de busqueda para: " + texto);

        if (texto.isEmpty()) {
            // Si está vacío, mostrar todo de nuevo
            cnx.entablar("SELECT * FROM vw_personal", TConsultas);
        } else {
            // Buscar por varias columnas, no solo nombre
            String[] columnas = {"nombre", "usuario", "tipoUsuario"};
            cnx.buscar("vw_personal", columnas, texto, TConsultas);
        }
    }//GEN-LAST:event_TBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAdmins;
    private javax.swing.JButton BBorrar;
    private javax.swing.JButton BEditar;
    private javax.swing.JButton BEdus;
    private javax.swing.JButton BNuevo;
    private javax.swing.JButton BTodos;
    private javax.swing.JLabel LDescripcion;
    private javax.swing.JTextField TBuscar;
    private javax.swing.JTable TConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
