package Admin.Panels;

import Util.Conexion;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author jli4n
 */
public class PAdRegistrosES extends javax.swing.JPanel {

    private Conexion cnx;
    String conteoEntradasMes = "SELECT * FROM vw_conteo_entradas_mes";
    String entradasYSalidas = "SELECT * FROM vw_entradas_salidas";

    /**
     * Creates new form AdminPersonal
     */
    public PAdRegistrosES(Conexion cnx) {
        this.cnx = cnx;
        initComponents();
        LDescripcion.setText("Listar todas las entradas y salidas");
        cnx.entablar(entradasYSalidas, TConsultas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        BTodos = new javax.swing.JButton();
        BHoy = new javax.swing.JButton();
        BEsteMomento = new javax.swing.JButton();
        CBTipo = new javax.swing.JComboBox<>();
        BConteoEnMes = new javax.swing.JButton();
        BReporte1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TConsultas = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel4 = new javax.swing.JLabel();
        CBMes = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setBorder(null);
        jToolBar2.setRollover(true);
        jToolBar2.setBorderPainted(false);

        BTodos.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BTodos.setText("TODOS");
        BTodos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTodos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTodosActionPerformed(evt);
            }
        });
        jToolBar2.add(BTodos);

        BHoy.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BHoy.setText("HOY");
        BHoy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BHoy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHoyActionPerformed(evt);
            }
        });
        jToolBar2.add(BHoy);

        BEsteMomento.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BEsteMomento.setText("EN ESTE MOMENTO");
        BEsteMomento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEsteMomento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BEsteMomento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEsteMomentoActionPerformed(evt);
            }
        });
        jToolBar2.add(BEsteMomento);

        CBTipo.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        CBTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "ENTRADA", "SALIDA" }));
        CBTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBTipoItemStateChanged(evt);
            }
        });
        jToolBar2.add(CBTipo);

        BConteoEnMes.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BConteoEnMes.setText("CONTEO EN MES");
        BConteoEnMes.setFocusable(false);
        BConteoEnMes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BConteoEnMes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BConteoEnMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConteoEnMesActionPerformed(evt);
            }
        });
        jToolBar2.add(BConteoEnMes);

        BReporte1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BReporte1.setText("REPORTE 1");
        BReporte1.setFocusable(false);
        BReporte1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BReporte1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BReporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReporte1ActionPerformed(evt);
            }
        });
        jToolBar2.add(BReporte1);

        jLabel1.setFont(new java.awt.Font("Anton", 0, 18)); // NOI18N
        jLabel1.setText("Admin / Registros de Entrada y Salida");

        LDescripcion.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        LDescripcion.setText("Descripción de consulta");

        TConsultas.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        TConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TConsultas.setMaximumSize(null);
        TConsultas.setMinimumSize(null);
        TConsultas.setPreferredSize(null);
        jScrollPane1.setViewportView(TConsultas);

        jToolBar1.setRollover(true);

        jLabel4.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel4.setText("Mes:");
        jToolBar1.add(jLabel4);

        CBMes.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        CBMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Enero", "Febrero", "Marzo", "Abril", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        CBMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBMesItemStateChanged(evt);
            }
        });
        jToolBar1.add(CBMes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(LDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTodosActionPerformed
        LDescripcion.setText("Listar todas las entradas y salidas");
        cnx.entablar(entradasYSalidas, TConsultas);
    }//GEN-LAST:event_BTodosActionPerformed

    private void BHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHoyActionPerformed
        LDescripcion.setText("Entradas y salidas hoy");
        String sql = "SELECT * FROM vw_entradas_salidas WHERE fecha = CURDATE()";
        cnx.entablar(sql, TConsultas);
    }//GEN-LAST:event_BHoyActionPerformed

    private void BReporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReporte1ActionPerformed
        String reporteConParametroMes = System.getProperty("user.dir") + "/conteo_entradas_mes.jasper";
        String reporteSinParametroMes = System.getProperty("user.dir") + "/conteo_entradas_agrupadas_mes.jasper";
        Map parametros = new HashMap();
        int mesNumero = CBMes.getSelectedIndex();

        if (mesNumero == 0) {
            System.out.println("Intentando abrir reporte: " + reporteSinParametroMes);
            if (cnx.ejecutarReporte(reporteSinParametroMes, parametros) == 0) {
                JOptionPane.showMessageDialog(this,
                        "Error al ejecutar el reporte.\nVerifique la consola para más detalles.\nArchivo: " + reporteSinParametroMes,
                        "Error en Reporte 1",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            parametros.put("mes", String.valueOf(mesNumero));

            System.out.println("Intentando abrir reporte: " + reporteConParametroMes);
            if (cnx.ejecutarReporte(reporteConParametroMes, parametros) == 0) {
                JOptionPane.showMessageDialog(this,
                        "Error al ejecutar el reporte.\nVerifique la consola para más detalles.\nArchivo: " + reporteConParametroMes,
                        "Error en Reporte 1",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BReporte1ActionPerformed

    private void BConteoEnMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConteoEnMesActionPerformed
        if (CBMes.getSelectedIndex() == 0) {
            LDescripcion.setText("Total de entradas y salidas del mes por infante");
            cnx.entablar(conteoEntradasMes, TConsultas);
            return;
        }

        int mesNumero = CBMes.getSelectedIndex();
        String sql = conteoEntradasMes + " WHERE mes = " + mesNumero;
        cnx.entablar(sql, TConsultas);
    }//GEN-LAST:event_BConteoEnMesActionPerformed

    private void CBMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBMesItemStateChanged
        if (CBMes.getSelectedIndex() == 0) {
            cnx.entablar(conteoEntradasMes, TConsultas);
            return;
        }

        int mesNumero = CBMes.getSelectedIndex();
        String sql = conteoEntradasMes + " WHERE mes = " + mesNumero;
        cnx.entablar(sql, TConsultas);
        LDescripcion.setText("Listar todas las del mes: " + mesNumero);
    }//GEN-LAST:event_CBMesItemStateChanged

    private void BEsteMomentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEsteMomentoActionPerformed
        LDescripcion.setText("Entradas y salidas en este momento");
        String sql = """
        SELECT 
            e.idInfante, 
            i.nombreinf AS Nombre, 
            e.fechaEntrada AS FechaEntrada, 
            e.horaEntrada AS HoraEntrada, 
            ed.nombreedu AS Educadora
        FROM entradas e
        JOIN infantes i ON e.idInfante = i.idInfante
        LEFT JOIN educadoras ed ON e.idEducadora = ed.idEducadora
        WHERE e.fechaEntrada = CURDATE()
          AND e.idInfante NOT IN (
              SELECT s.idInfante 
              FROM salidas s 
              WHERE s.fechaSalida = CURDATE()
          );
    """;
        cnx.entablar(sql, TConsultas);
    }//GEN-LAST:event_BEsteMomentoActionPerformed

    private void CBTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBTipoItemStateChanged
        String tipo = CBTipo.getSelectedItem().toString();

        String sql;
        if (tipo.equals("ENTRADA")) {
            sql = """
                SELECT 
                    e.idEntrada AS ID,
                    i.nombreinf AS Infante,
                    e.fechaEntrada AS Fecha,
                    e.horaEntrada AS Hora,
                    ed.nombreedu AS Educadora
                FROM entradas e
                JOIN infantes i ON e.idInfante = i.idInfante
                LEFT JOIN educadoras ed ON e.idEducadora = ed.idEducadora
                ORDER BY e.fechaEntrada DESC, e.horaEntrada DESC;
            """;
            LDescripcion.setText("Listar todas las entradas");
            cnx.entablar(sql, TConsultas);
        } else if (tipo.equals("SALIDA")) {
            sql = """
                SELECT 
                    s.idSalida AS ID,
                    i.nombreinf AS Infante,
                    s.fechaSalida AS Fecha,
                    s.horaSalida AS Hora,
                    s.tipoAutorizado AS TipoAutorizado,
                    ed.nombreedu AS Educadora
                FROM salidas s
                JOIN infantes i ON s.idInfante = i.idInfante
                LEFT JOIN educadoras ed ON s.idEducadora = ed.idEducadora
                ORDER BY s.fechaSalida DESC, s.horaSalida DESC;
            """;
            LDescripcion.setText("Listar todas las salidas");
            cnx.entablar(sql, TConsultas);
        } else {
            LDescripcion.setText("Listar todas las entradas y salidas");
            cnx.entablar(entradasYSalidas, TConsultas);
        }
    }//GEN-LAST:event_CBTipoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BConteoEnMes;
    private javax.swing.JButton BEsteMomento;
    private javax.swing.JButton BHoy;
    private javax.swing.JButton BReporte1;
    private javax.swing.JButton BTodos;
    private javax.swing.JComboBox<String> CBMes;
    private javax.swing.JComboBox<String> CBTipo;
    private javax.swing.JLabel LDescripcion;
    private javax.swing.JTable TConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
