
public class FAdmin extends javax.swing.JFrame {

    Conexion cnx;
    String id;
    String nombre;
    PAdPersonal pPersonal;

    public FAdmin() {
        initComponents();

        setLocationRelativeTo(this);
    }

    public void recibirDatos(Conexion cnx, String id, String nombre) {
        this.cnx = cnx;
        this.id = id;
        this.nombre = nombre;

        LId.setText("ID: " + id);
        LNombre.setText(nombre);
        
        pPersonal = new PAdPersonal(this.cnx);
        PContenedor.add(pPersonal);
        PContenedor.revalidate();
        PContenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LId = new javax.swing.JLabel();
        LNombre = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BPersonal = new javax.swing.JButton();
        BInfantes = new javax.swing.JButton();
        BEncargados = new javax.swing.JButton();
        BRegistrosES = new javax.swing.JButton();
        PContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administradores");

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        LId.setFont(new java.awt.Font("Anton", 0, 18)); // NOI18N
        LId.setForeground(new java.awt.Color(255, 255, 255));
        LId.setText("ID:");

        LNombre.setFont(new java.awt.Font("Anton", 0, 18)); // NOI18N
        LNombre.setForeground(new java.awt.Color(255, 255, 255));
        LNombre.setText("NOMBRE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(LId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 730, Short.MAX_VALUE)
                .addComponent(LNombre)
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LId)
                    .addComponent(LNombre))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        BPersonal.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        BPersonal.setText("PERSONAL");
        BPersonal.setBorder(null);
        BPersonal.setBorderPainted(false);
        BPersonal.setContentAreaFilled(false);
        BPersonal.setDefaultCapable(false);
        BPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPersonalActionPerformed(evt);
            }
        });

        BInfantes.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        BInfantes.setText("INFANTES");
        BInfantes.setBorder(null);
        BInfantes.setBorderPainted(false);
        BInfantes.setContentAreaFilled(false);
        BInfantes.setDefaultCapable(false);
        BInfantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInfantesActionPerformed(evt);
            }
        });

        BEncargados.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        BEncargados.setText("ENCARGADOS");
        BEncargados.setBorder(null);
        BEncargados.setBorderPainted(false);
        BEncargados.setContentAreaFilled(false);
        BEncargados.setDefaultCapable(false);
        BEncargados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEncargadosActionPerformed(evt);
            }
        });

        BRegistrosES.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        BRegistrosES.setText("REGISTROS E/S");
        BRegistrosES.setBorder(null);
        BRegistrosES.setBorderPainted(false);
        BRegistrosES.setContentAreaFilled(false);
        BRegistrosES.setDefaultCapable(false);
        BRegistrosES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegistrosESActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BRegistrosES)
                    .addComponent(BEncargados)
                    .addComponent(BPersonal)
                    .addComponent(BInfantes))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BInfantes)
                .addGap(18, 18, 18)
                .addComponent(BEncargados)
                .addGap(18, 18, 18)
                .addComponent(BPersonal)
                .addGap(18, 18, 18)
                .addComponent(BRegistrosES)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        PContenedor.setBackground(new java.awt.Color(51, 51, 51));
        PContenedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PContenedor.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        PContenedor.setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BInfantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInfantesActionPerformed
        PContenedor.removeAll();
        PContenedor.add(new PAdInfantes(this.cnx));
        PContenedor.revalidate(); // recalcula el layout
        PContenedor.repaint(); // repinta la interfaz
    }//GEN-LAST:event_BInfantesActionPerformed

    private void BEncargadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEncargadosActionPerformed
        PContenedor.removeAll();
        PContenedor.add(new PAdEncargados(this.cnx));
        PContenedor.revalidate(); // recalcula el layout
        PContenedor.repaint(); // repinta la interfaz
    }//GEN-LAST:event_BEncargadosActionPerformed

    private void BPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPersonalActionPerformed
        PContenedor.removeAll();
        PContenedor.add(pPersonal);
        PContenedor.revalidate(); // recalcula el layout
        PContenedor.repaint(); // repinta la interfaz
    }//GEN-LAST:event_BPersonalActionPerformed

    private void BRegistrosESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegistrosESActionPerformed
        PContenedor.removeAll();
        PContenedor.add(new PAdRegistrosES(this.cnx));
        PContenedor.revalidate(); // recalcula el layout
        PContenedor.repaint(); // repinta la interfaz
    }//GEN-LAST:event_BRegistrosESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEncargados;
    private javax.swing.JButton BInfantes;
    private javax.swing.JButton BPersonal;
    private javax.swing.JButton BRegistrosES;
    private javax.swing.JLabel LId;
    private javax.swing.JLabel LNombre;
    private javax.swing.JPanel PContenedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
