/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author jli4n
 */
public class PAdRegistrosES extends javax.swing.JPanel {

    private Conexion cnx;

    /**
     * Creates new form AdminPersonal
     */
    public PAdRegistrosES(Conexion cnx) {
        this.cnx = cnx;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        BTodos = new javax.swing.JButton();
        BHoy = new javax.swing.JButton();
        BEsteMomento = new javax.swing.JButton();
        BEntrada = new javax.swing.JButton();
        BSalida = new javax.swing.JButton();
        BReporte1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TConsultas = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel3 = new javax.swing.JLabel();
        CBDia = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        CBMes = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setBorder(null);
        jToolBar2.setRollover(true);
        jToolBar2.setBorderPainted(false);

        BTodos.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BTodos.setText("TODOS");
        BTodos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTodos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTodosActionPerformed(evt);
            }
        });
        jToolBar2.add(BTodos);

        BHoy.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BHoy.setText("HOY");
        BHoy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BHoy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHoyActionPerformed(evt);
            }
        });
        jToolBar2.add(BHoy);

        BEsteMomento.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        BEsteMomento.setText("EN ESTE MOMENTO");
        BEsteMomento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEsteMomento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(BEsteMomento);

        BEntrada.setText("DE ENTRADA");
        BEntrada.setFocusable(false);
        BEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEntrada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(BEntrada);

        BSalida.setText("DE SALIDA");
        BSalida.setFocusable(false);
        BSalida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BSalida.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(BSalida);

        BReporte1.setText("REPORTE 1");
        BReporte1.setFocusable(false);
        BReporte1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BReporte1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BReporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReporte1ActionPerformed(evt);
            }
        });
        jToolBar2.add(BReporte1);

        jLabel1.setFont(new java.awt.Font("Anton", 0, 18)); // NOI18N
        jLabel1.setText("Admin / Registros de Entrada y Salida");

        jLabel2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel2.setText("Descripción de consulta");

        TConsultas.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        TConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TConsultas.setMaximumSize(null);
        TConsultas.setMinimumSize(null);
        TConsultas.setPreferredSize(null);
        jScrollPane1.setViewportView(TConsultas);

        jToolBar1.setRollover(true);

        jLabel3.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel3.setText("Día:");
        jToolBar1.add(jLabel3);

        CBDia.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        CBDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes" }));
        jToolBar1.add(CBDia);

        jLabel4.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        jLabel4.setText("Mes:");
        jToolBar1.add(jLabel4);

        CBMes.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        CBMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Enero", "Febrero", "Marzo", "Abril", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jToolBar1.add(CBMes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTodosActionPerformed

    private void BHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHoyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BHoyActionPerformed

    private void BReporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReporte1ActionPerformed
        String reporteConParametroMes = System.getProperty("user.dir") + "/conteo_entradas_mes.jasper";
        String reporteSinParametroMes = System.getProperty("user.dir") + "/conteo_entradas_agrupadas_mes.jasper";
        Map parametros = new HashMap();
        int mesNumero = CBMes.getSelectedIndex();

        if (mesNumero == 0) {
            System.out.println("Intentando abrir reporte: " + reporteSinParametroMes);
            if (cnx.ejecutarReporte(reporteSinParametroMes, parametros) == 0) {
                JOptionPane.showMessageDialog(this,
                        "Error al ejecutar el reporte.\nVerifique la consola para más detalles.\nArchivo: " + reporteSinParametroMes,
                        "Error en Reporte 1",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            parametros.put("mes", String.valueOf(mesNumero));

            System.out.println("Intentando abrir reporte: " + reporteConParametroMes);
            if (cnx.ejecutarReporte(reporteConParametroMes, parametros) == 0) {
                JOptionPane.showMessageDialog(this,
                        "Error al ejecutar el reporte.\nVerifique la consola para más detalles.\nArchivo: " + reporteConParametroMes,
                        "Error en Reporte 1",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BReporte1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEntrada;
    private javax.swing.JButton BEsteMomento;
    private javax.swing.JButton BHoy;
    private javax.swing.JButton BReporte1;
    private javax.swing.JButton BSalida;
    private javax.swing.JButton BTodos;
    private javax.swing.JComboBox<String> CBDia;
    private javax.swing.JComboBox<String> CBMes;
    private javax.swing.JTable TConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
